---
- name: Create project directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ wordpress.root }}"
    - /etc/nginx/conf.d

- name: Copy compose file
  become: true
  check_mode: false
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ wordpress.root }}/docker-compose.yaml"
    mode: "0644"

- name: Copy wordpress nginx configurations
  become: true
  check_mode: false
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
    mode: "0644"

- name: Test registry compose file
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "docker compose config -f {{ wordpress.root }}/docker-compose.yaml"
  changed_when: false
  failed_when: false

- name: Docker compose up wordpress
  check_mode: false
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ wordpress.root }}"
    wait: true
  environment: "{{ proxy_env }}"

- name: Restarting Nginx container
  become: true
  check_mode: false
  community.docker.docker_container:
    name: nginx
    state: started
    restart: true
