---
- name: Set Cloudflares New <A> Records
  become: true
  check_mode: false
  community.general.cloudflare_dns:
    solo: true
    state: present
    timeout: 60
    type: A
    zone: "{{ root_domain }}"
    api_token: "{{ cloudflare_dns.api_token }}"
    account_api_key: "{{ cloudflare_dns.account_token }}"
    account_email: "{{ cloudflare_dns.account_email }}"
    record: "{{ item }}"
    value: "{{ ansible_host }}"
  loop:
    - "{{ wordpress.subdomain }}"
    - "{{ registry.subdomain }}"

- name: Create certificates directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/certs/{{ root_domain }}
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  tags: ssl

- name: Add private key
  become: true
  ansible.builtin.template:
    src: privkey.pem.j2
    dest: "/etc/certs/{{ root_domain }}/privkey.pem"
    owner: root
    group: root
    mode: "0644"
  tags: ssl

- name: Add full-chain certificate
  become: true
  check_mode: false
  ansible.builtin.copy:
    src: fullchain.pem
    dest: "/etc/certs/{{ root_domain }}/fullchain.pem"
    owner: root
    group: root
    mode: "0644"
  tags: ssl
